# Зарезервированная переменная (версия докера)
version: '3'

# Зарезервированная переменная докера
# >> docker-compose up -d
# >> docker exec -it nginx bash # подсоеденится к контейнеру
services:
  docker_nginx:
    container_name: docker_nginx
    image: nginx:latest
    restart: always
    ports:
      - "8876:80"
    volumes:
    - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    - ./:/app

  docker_php:
    container_name: docker_php
    image: php:latest
    restart: always

  docker_mysql:
    container_name: docker_mysql
    image: mysql:8.0
    restart: always
    ports:
    - 8181:3306
    environment:
      MYSQL_DATABASE: chat
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: chad
      MYSQL_PASSWORD: char
    volumes:
      - ./tmp/db:/var/lib/mysql
    command: mysqld: --charset-set-server=utf8 --colation-server=utf8_unicode_ci

  docker_redis:
    container_name: docker_redis
    image: redis

  docker_adminer:
    container_name: docker_adminer
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: docker_mysql
    ports:
    - 5114:8080