version: '3.0'

services:

    # http://localhost:8010/
    # docker exec -it <container_id (server-apache)> bash
    server-apache-81:
        container_name: server-apache-81
        restart: always
        build: ./.docker/server-apache
        volumes:
            - '.:/var/www/html'
            - '.docker/server-apache/conf/php.ini:/usr/local/etc/php/conf.d/php.ini'
            - '.docker/server-apache/conf:/etc/supervisor/conf.d/supervisord.conf'
        ports:
            - '80:80'
            - '443:443'
        # command: npm run debug

#    mailhog:
#        image: 'mailhog/mailhog:latest'
#        ports:
#            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
#            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
#        networks:
#            - sail
