version: '3.9'

services:

    web-nginx:
        container_name: ${DOCKER_NAME}-web-nginx
        build:
            context: .
            dockerfile: .docker/web-nginx/Dockerfile
        ports:
            - 80:80
            - 433:433
        volumes:
           - .docker/web-nginx/nginx.conf:/etc/nginx/conf.d/default.conf
           - ./:/var/www/html/
        links:
            - web-php-fpm

    web-php-fpm:
        container_name: ${DOCKER_NAME}-web-php-fpm
        build:
            context: .
            dockerfile: .docker/web-php-fpm/Dockerfile
        ports:
            - 9000:9000
        volumes:
            - ./:/var/www/html/

    web-node:
        container_name: ${DOCKER_NAME}-web-node
        build:
            context: .
            dockerfile: .docker/web-node/Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - ./:/var/www/html/

    db-mysql:
        container_name: ${DOCKER_NAME}-db-mysql
        image: mysql:8.0.25
        command:
            - mysqld
            - '--default-authentication-plugin=mysql_native_password'
            - '--character-set-server=utf8'
            - '--collation-server=utf8_unicode_ci'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD_ROOT}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - db-mysql:/var/lib/mysql
        ports:
            - '3306:3306'
        extra_hosts:
            - "host.docker.internal:host-gateway"

    db-redis:
        container_name: ${DOCKER_NAME}-db-redis
        image: redis:7.2.1
        volumes:
            - db-redis:/data
        ports:
            - '6379:6379'
        extra_hosts:
            - "host.docker.internal:host-gateway"

    db-memcached:
        container_name: ${DOCKER_NAME}-db-memcached
        image: memcached:1.6.22
        environment:
            MEMCACHED_MAX_CONNECTIONS: 2000
        ports:
            - '11211:11211'
        extra_hosts:
            - "host.docker.internal:host-gateway"

    db-mongodb:
        container_name: ${DOCKER_NAME}-db-mongodb
        image: mongo:4.2.3-bionic
        environment:
            MONGO_INITDB_DATABASE: '${DB_DATABASE}'
            MONGO_INITDB_ROOT_USERNAME: '${DB_USERNAME}'
            MONGO_INITDB_ROOT_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - db-mongodb:/data/db
        ports:
            - '27017:27017'
        extra_hosts:
            - "host.docker.internal:host-gateway"

volumes:
    db-mysql:
    db-redis:
    db-mongodb:
