version: '3.9'
services:
  db-mysql:
    image: mysql
    container_name: db-mysql
    command:
      - mysqld
      - '--default-authentication-plugin=mysql_native_password'
      - '--character-set-server=utf8'
      - '--collation-server=utf8_unicode_ci'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD_ROOT}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'db_data_mysql:/var/lib/mysql'
      - 'db_data_mysql_backup:/docker-entrypoint-initdb.d'
  web-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: web-phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - '8012:80'
  web-adminer:
    image: adminer
    container_name: web-adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db-mysql
    ports:
      - '8013:8080'
volumes:
  db_data_mysql:
    name: db-data-mysql
  db_data_mysql_backup:
    name: db-data-mysql-backup
