version: '3.0'

services:

    # php -i | grep PDO
    # http://localhost:8011/
    # docker exec -it <container_id (php-apache)> bash
    php-apache-81:
        container_name: php-apache-81
        restart: always
        build: ./.docker/php-apache
        volumes:
            - '.:/var/www/html'
            - '.docker/php-apache/conf/php.ini:/usr/local/etc/php/conf.d/php.ini'
        ports:
            - '8010:80'
        # command: npm run debug
