# Зарезервированная переменная (версия докера)
version: '3'

# Зарезервированная переменная докера
# >> docker-compose up -d
# >> docker exec -it nginx bash # подсоеденится к контейнеру
services:
  project_nginx:
    container_name: project_nginx
    image: nginx:latest
    restart: always
    ports:
      - "8876:80"
    volumes:
    - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    - ./:/app

  project_php:
    container_name: project_php
    image: php:latest
    restart: always

  project_db_mysql:
    container_name: project_db_mysql
    image: mysql:8.0
    restart: always
    ports:
    - 8181:3306
    environment:
      MYSQL_DATABASE: chat
      MYSQL_USER: chad
      MYSQL_PASSWORD: char
      MYSQL_ROOT_PASSWORD: roots
    volumes:
      - ./tmp/db:/var/lib/mysql
      command: mysqld: --charset-set-server=utf8 --colation-server=utf8_unicode_ci

  project_redis:
    container_name: project_redis
    image: redis

  project_adminer:
    container_name: project_adminer
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: project_db_mysql
    ports:
    - 5114:8080