version: '3.9'
services:

  #################################
  # http://localhost:8001/
  #################################
  adminer:
    container_name: ${DOCKER_NAME}-gui-adminer
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db-mysql
    ports:
      - '1001:8080'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  ################################
  # http://localhost:8002/
  ################################
  redis-commander:
    container_name: ${DOCKER_NAME}-gui-redis-commander
    image: rediscommander/redis-commander:latest
    ports:
      - '1002:8081'
    environment:
      REDIS_HOSTS: redis1:maptex-db-redis:6379:0:changeme
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  #################################
  # http://localhost:8003/
  #################################
  memcached-admin:
    container_name: ${DOCKER_NAME}-gui-memcached-admin
    image: hatamiarash7/memcached-admin:latest
    ports:
      - "1003:80"
    environment:
      - MEMCACHED_HOST=maptex-db-memcached
      - MEMCACHED_PORT=11211
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  #################################
  # http://localhost:8004/
  #################################
#  mongoclient:
#    container_name: ${DOCKER_NAME}-gui-mongoclient
#    image: fabianlee/my-mongoclient:3.9
#    ports:
#      - "1004:80"
#    extra_hosts:
#      - 'host.docker.internal:host-gateway'
