version: '3.9'

services:

    web-nginx:
        container_name: web-nginx
        build:
            context: .
            dockerfile: .docker/web-nginx/Dockerfile
            args:
                - CERTBOT_EMAIL=feedback@mosprofleader.ru
                - DOMAIN_LIST=mosprofleader.ru
        ports:
            - 443:443
            - 80:80
        volumes:
            - .docker/web-nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
        restart: always
        links:
            - web-php-fpm

    web-php-fpm:
        container_name: web-php-fpm
        build:
            context: .
            dockerfile: .docker/web-php-fpm/Dockerfile
        ports:
            - 9000:9000
        volumes:
            - ./:/var/www/html/

    web-certbot:
        container_name: web-certbot
        image: certbot/certbot
        depends_on:
            - web-nginx
        # command: >
        #    certonly
        #      --preferred-challenges=dns
        #      --domain ${DOMAIN_URL}
        #      --email ${DOMAIN_EMAIL} --agree-tos --no-eff-email --staging
        #      --agree-tos
        # volumes:
        #    - ./certbot/scripts/authenticator.sh:/app/authenticator.sh
        #    - ./certbot/etc/letsencrypt:/etc/letsencrypt
        #    - ./certbot/data:/var/www/html/certbot
        #    - ./certbot/logs:/var/log/letsencrypt
        #    - ./certbot/conf/:/etc/letsencrypt
        #    - ./certbot/www:/var/www/html/certbot

    db-mysql-mosprofleader-ru:
        container_name: db-mysql-mosprofleader-ru
        image: mysql:5.7
        command:
            - mysqld
            - '--default-authentication-plugin=mysql_native_password'
            - '--character-set-server=utf8'
            - '--collation-server=utf8_unicode_ci'
            # - '--sql-mode="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"'
        environment:
            MYSQL_ROOT_PASSWORD: mosprof_password
            MYSQL_DATABASE: mosprof_db
            MYSQL_USER: mosprof_user
            MYSQL_PASSWORD: mosprof_password
        volumes:
            - db-mysql-mosprofleader-ru:/var/lib/mysql
        ports:
            - '3306:3306'

    gui-adminer-mosprofleader-ru:
        container_name: gui-adminer-mosprofleader-ru
        image: adminer
        restart: always
        environment:
            ADMINER_DEFAULT_SERVER: db-mysql-mosprofleader-ru
        ports:
            - '1001:8080'

volumes:
    db-mysql-mosprofleader-ru: