version: '3.9'

services:

  web-server:
    build:
      dockerfile: .docker/Dockerfile
      context: .
    stdin_open: true
    tty: true
    volumes:
      # - '.docker/conf/php.ini:/usr/local/etc/php/conf.d/php.ini'
      - '.:/var/www/html'
    ports:
      - '80:80'

  db-mysql-mosprof:
    container_name: db-mysql-mosprof
    image: mysql:8.0.25
    command:
      - mysqld
      - '--default-authentication-plugin=mysql_native_password'
      - '--character-set-server=utf8'
      - '--collation-server=utf8_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: mosprof_password
      MYSQL_DATABASE: mosprof_db
      MYSQL_USER: mosprof_user
      MYSQL_PASSWORD: mosprof_password
    volumes:
      - db-mysql-mosprof:/var/lib/mysql
    ports:
      - '3306:3306'

  gui-adminer:
    container_name: gui-adminer
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db-mysql-mosprof
    ports:
      - '1001:8080'

volumes:
    db-mysql-mosprof: