FROM node:18
WORKDIR /var/www

# Install gulp & bower
RUN npm install --global electron-forge
RUN npm install --global gulp
RUN npm install --global grunt
RUN npm install --global bower
RUN npm install --global less
RUN npm install --global sass

# Установка прав доступа (linux ubuntu)
# su -l node -s /bin/bash
